-- Execute este script no SQL Editor do Supabase para criar as tabelas necessárias

-- Tabela de PUBLICAÇÕES
CREATE TABLE IF NOT EXISTS publications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    author TEXT NOT NULL,
    image_url TEXT NOT NULL,
    publication_url TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Tabela de MEMBROS
CREATE TABLE IF NOT EXISTS members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    role TEXT NOT NULL,
    image_url TEXT NOT NULL,
    lattes_url TEXT,
    research_topic TEXT,
    category TEXT NOT NULL, -- 'coordenadores', 'colaboradores', etc.
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Tabela de USUÁRIOS ADMIN
CREATE TABLE IF NOT EXISTS admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL, -- Em um cenário real, armazene apenas o HASH da senha
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Inserir usuário admin padrão (Se não existir)
-- Senha padrão exemplo: 'fisica' (Recomenda-se alterar depois)
INSERT INTO admin_users (username, password_hash)
VALUES ('ADM', 'fisica')
ON CONFLICT (username) DO NOTHING;

-- Configurar Storage (Buckets)
-- Nota: Buckets geralmente são criados via Interface ou API, mas podemos definir políticas aqui se necessário.
-- Vá em Storage -> New Bucket -> crie 'members-images' e 'publications-images', e marque como "Public".
